### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [nataliaraspberries/fashion_blog_natalia#1]
Natalia,

Nice job on this! Looks great. A couple of recommendations for you:
- Make sure you are reusing CSS selectors / classes as much as possible. Something like this:

``` css
.content1{
        width: 66.6%;
        height: 27.9%;
        border: #CCCCCC 0px solid;
        position:relative;
      }
  .content2{
        width: 33%;
        height: 300px;
        border: #CCCCCC 0px solid;
        position: absolute;
      }
```

could be refactored using the comma syntax to share properties across selectors:

``` css
.content1, .content2 {
    Styles here
}
```
- Make sure you're using indentation to make your code more readable. The auto indent feature makes it easy through Atom.
